### ISSUE TITLE
I'd like to confirm contribute rules.

### ISSUE THREAD

**Issue by xiangyangyuan** [Olament/bililive#1]
Hi Olament,
This is a fantastic project.
Would you please share if it's possible to know details of contribution rules or there's any chatroom or work group for current repo bililive?
I'd like to do some improvement in frontside since I had some exp in echarts, which is a wonderful visualization lib for js.
And also exp for some angular js and bootstrapt. 

Thanks for going through the ticket. 
Looking forward to your reply.

**Comment by Olament** [comment]
感谢，

现在这个项目只有我在维护，所以没有相关的讨论组。如果以后有多个开发者参与这个项目的话，我可以考虑开设对应的 discord channel 或者 QQ 群。现在关于开发的讨论可以在本项目的 ```Discussions``` 区域进行。

现在前端确实有一些工作要做，我的下一个目标是移除掉 ```ant-design-pro``` 依赖。目前 ```ant-design-pro``` 被用来实现主播详情页下的同接趋势，弹幕趋势，和收入趋势功能。但是 ```ant-design-pro``` 本身已经被开发组废弃了，常年没有人维护。我的计划是用 ```BizCharts``` 来代替现有的 ```MiniArea``` 组件。

**Comment by xiangyangyuan** [comment]
感谢回复。
如果方便的话还是希望能有一个discord 用来快捷的交流以便于迭代页面的设计等。
基于Discussions的讨论速度以及分享方法着实有点不够快捷，所以期待您的discord channel 号。

**Comment by Olament** [comment]
flyingelement[0409]

**Comment by xiangyangyuan** [comment]
我已近在discord申请好友，这边的票就先close了。
十分感谢回答。
